### ISSUE TITLE
Renderer components functions are being called, not rendered.

### ISSUE THREAD

**Issue by glenjamin** [rexxars/commonmark-react-renderer#12]
I just tried using a custom component, but I was passing a createClass-style component and got an error.

It looks like although you have defined the new renderers as functional components, they're being called as functions rather than `createElement`.

Is this intentional? I'll send a PR shortly with a suggested change, I reckon there should be a `createElement` call here: https://github.com/rexxars/commonmark-react-renderer/blob/master/src/commonmark-react-renderer.js#L233

**Comment by rexxars** [comment]
Yup, total oversight on my part. Just looking at the same thing myself, actually, but feel free to send a PR if you have time :+1:

**Comment by rexxars** [comment]
Need to add tests to ensure that this works with:
1. Function components
2. `React.createClass`-style components
3. ES6-style `class Foo extends React.Component`

**Comment by rexxars** [comment]
I think there might have been a thought behind this, seeing as the tests all pass functions that return an element, but this seems really cumbersome, so I think it definitely should be changed.

**Comment by glenjamin** [comment]
Ah, I see you've just sorted this!

I had started, but hit a bit of a wall with the text component - https://github.com/glenjamin/commonmark-react-renderer/tree/renderers-as-components

Specialcasing it seems reasonable.

**Comment by rexxars** [comment]
Yeah, it turned out to be trickier than I thought. I think this is an acceptable solution for now - if someone comes up with a cleaner approach I'd be happy to accept it :-)

Thanks for reporting!

**Comment by glenjamin** [comment]
One thing I did do on the branch which I think is useful, is using tagname strings instead of `getDomRenderer` - as they get passed as the first arg to createElement this works.

**Comment by glenjamin** [comment]
eg.
https://github.com/glenjamin/commonmark-react-renderer/commit/63a788932807cfa3fad4d9cd39843e06d59bbda5#diff-98e71445e714758aefab394258629a72R16
https://github.com/glenjamin/commonmark-react-renderer/commit/63a788932807cfa3fad4d9cd39843e06d59bbda5#diff-98e71445e714758aefab394258629a72R220

**Comment by rexxars** [comment]
Ah, clever! Could you send a pull request for that?

**Comment by glenjamin** [comment]
Yup, will sort it now
