### ISSUE TITLE
How to enable the `smart` option from Commonmark?

### ISSUE THREAD

**Issue by ianstormtaylor** [rexxars/commonmark-react-renderer#15]
Hey, I'd like to get "smart" quotes and em-dashes automatically, like Commonmark allows when the [`smart` option](https://github.com/jgm/commonmark.js/tree/eb14f5f854ad5b38e6dba536dd192c3642d5a649#usage) is enabled. How can I do that?

**Comment by rexxars** [comment]
Shouldn't be hard to add, but if this is intended for use within react-markdown, I'd rather not add it as I am experimenting with replacing the parser with something that doesn't use commonmark...

Sorry about that.

**Comment by Jpunt** [comment]
I need this as well. Is the experimentation fase over and can we add it please?

**Comment by rexxars** [comment]
There's an undocumented, hidden prop called `parserOptions`.
```js
var source = '"Aye, smart? -- for sure!"'
<Markdown
  source={source}
  parserOptions={{smart: true}}
/>

// “Aye, smart? – for sure!”
```

I'm in the process of "forking" this module and creating [react-commonmark](https://www.npmjs.com/package/react-commonmark), which will have this as a defined and documented feature, while react-markdown will change to a markdown parser and will not have this `smart`-feature in the future.

**Comment by Jpunt** [comment]
I think that you're confusing `commonmark-react-renderer` with `react-commonmark` (or I am 😅). But because of your example code I've found out that it's already possible, because I've got access to the actual commonmark-parser:

```js
const parser = new CommonMark.Parser({smart: true});
const renderer = new ReactRenderer({...})
```

Thanks, this is solved for me! 🎉
