### ISSUE TITLE
commonmark peer dependency

### ISSUE THREAD

**Issue by Yomguithereal** [rexxars/commonmark-react-renderer#21]
Hello @rexxars. I don't know if `commonmark-react-renderer` still works with `commonmark` v0.26.0 but if it's the case, it would be nice to update the peer dependencies of the lib.

**Comment by schickling** [comment]
It does indeed **not** work with commonmark 0.26.0.

**Comment by rexxars** [comment]
Are there any specific reasons why you want to use 0.26? They've changed all the node types from PascalCase to snake_case, which means I'll either have to translate them back and forth in all hooks and options, or make a breaking change to both `commonmark-react-renderer` and `react-markdown`.

**Comment by schickling** [comment]
I think it just makes sense to move forward based on the underlying dependencies. If commonmark introduced a breaking change, I think it's fair to justify one for this project as well. But these are just my two cents :)

**Comment by rexxars** [comment]
It's hard to communicate to users why I'm doing a breaking change that require them to rewrite a lot of their code when the benefits are small edge-cases such as tab handling. I'll think about it.

**Comment by Yomguithereal** [comment]
One other option would be to support both versions by just aliasing node types (using lodash's case helpers it should be quite simple to do).

**Comment by rgbkrk** [comment]
I've been wondering the same, more than happy to adjust my code to match a major version bump (which technically 0.25 -> 0.26 is... 🙍).

**Comment by rexxars** [comment]
Released 4.3.1. It should be backwards-compatible.

**Comment by Yomguithereal** [comment]
Thanks @rexxars!
