### ISSUE TITLE
How can I change the wrapping type of the result?

### ISSUE THREAD

**Issue by lucas-aragno** [rexxars/commonmark-react-renderer#25]
Hey

I'm trying to use this library to render some html near to a link right now it works but it renders the result wrapped inside a `<p>` and I would like to use a span. The readme says about setting the `type` but im doing in like `new ReactRenderer({type: 'span'})` and `renderer.render(parser.parse(defaultTextString), { type: 'span' })` but I'm still getting the `<p>` what am I missing?

**Comment by rexxars** [comment]
All "plain lines" in markdown are paragraphs by definition. If you have a very specific use case where you're never going to be rendering any paragraphs, you can override the paragraph renderer:

```js
var CommonMark = require('commonmark');
var ReactRenderer = require('commonmark-react-renderer');

var parser = new CommonMark.Parser();
var renderer = new ReactRenderer({
  renderers: {
    Paragraph: function(props) {
      return React.createElement('span', null, props.children);
    }
  }
});

var input = 'Some [link](https://github.com/rexxars/commonmark-react-renderer) here';
var ast = parser.parse(input);
var result = renderer.render(ast); // Array of nodes, index 0 should be a span
```
