### ISSUE TITLE
On the subject of keys

### ISSUE THREAD

**Issue by Yomguithereal** [rexxars/commonmark-react-renderer#3]
Hello @rexxars. Thanks for this awesome renderer! Just had a little issue with it: could it be possible to give keys to the resulting array of elements (either index-based or giving the user the possibility to set it using a function)?

**Comment by Yomguithereal** [comment]
I can fiddle a PR on the subject if you want.

**Comment by rexxars** [comment]
Feel free to try and come up with a PR, just keep in mind that index-based keys probably won't be the right solution (see "[Index as a key is an anti-pattern](https://medium.com/@robinpokorny/index-as-a-key-is-an-anti-pattern-e0349aece318)"). Not really sure how you'd make any sane key for a markdown document, to be honest...

**Comment by Yomguithereal** [comment]
Sure, this would be kind of difficult to find a proper key but I am some use cases that might work (some precise elements such as images etc. would have a key while others don't). The thing is React is a bit overzealous and yell into the console that keys should be in place.

**Comment by rexxars** [comment]
Just remember that warnings are just that: warnings - and is not shown in production. It doesn't mean that there is necessarily a good solution to the problem.

Also, even for images, be sure to include both source URL and title attribute, along with an index. With that, I will slowly back away from this and let you come up with a proposal :+1:

**Comment by Yomguithereal** [comment]
> Just remember that warnings are just that: warnings - and is not shown in production. It doesn't mean that there is necessarily a good solution to the problem.

Sure. Guess it is some kind of OCD. I am having hard times with console warnings that could not be there :).

Thanks anyway @rexxars. I'll try to come up with a proposition soon.

**Comment by glenjamin** [comment]
The problem with ignoring warnings is that they create noise, which can mask genuine warnings, and train people to not worry about them.

For this reason, I think anything with a sensible unique key as part of it's data should use that key.

There are two scenarios where using naive index-based keys cause problems, when your component has state (including implicit DOM state), and when you have behaviour on the didMount/didUnMount lifecycle events.

I believe that neither of these affect markdown rendering, so index-as-keys on elements which have no other identifying data should be safe.

**Comment by rexxars** [comment]
As-is, indexed keys should work fine. Down the line, I want to add support for syntax highlighting, among other features, which will require more complex components that might hold state. I'll tackle this when I get there though - feel free to just use index keys for now.

**Comment by Yomguithereal** [comment]
Ok. I started looking at the code. Do we agree that we would need key only at top level. I.e. the returned children but not the children of those children?

**Comment by glenjamin** [comment]
What does React warn on? Ideally we'd want to silence any warnings.

**Comment by rexxars** [comment]
If the goal is to prevent warnings, everything child will need an index, surely? Regardless of depth? Or am I not thinking about this correctly?

**Comment by Yomguithereal** [comment]
If I recall correctly, React will only warn on the first level and not bother with sub-children.

**Comment by rexxars** [comment]
Released 2.2.2 with the key changes.

**Comment by Yomguithereal** [comment]
Thanks @rexxars. I'll try to help with code highlight soon.
