### ISSUE TITLE
How to add class names to markdown components?

### ISSUE THREAD

**Issue by GAumala** [rexxars/commonmark-react-renderer#33]
I want to control the style of the markdown components using CSS classes. I'm setting the `className` prop to every component like this:

```javascript
import React from 'react'
import CommonMark from 'commonmark';
import ReactRenderer from 'commonmark-react-renderer'

const parser = new CommonMark.Parser();
const renderer = new ReactRenderer();

const setMarkdownCSSClassToComponentFunc = (className) => {
  return (component) => React.cloneElement(component, { className })
}

const markdownToComponentArray = (markdownSource, markdownClass) => {
  const ast = parser.parse(markdownSource)
  const componentArray = renderer.render(ast);
  const setMarkdownCSSClassToComponent = setMarkdownCSSClassToComponentFunc(markdownClass)
  return componentArray.map(setMarkdownCSSClassToComponent)
}

export default markdownToComponentArray
```

This seems to work fine with `<p>` elements, but it doesn't work at all with other elements like `<h2>` or `<pre>`. Can anyone please give me any suggestions?

**Comment by rexxars** [comment]
I just pushed v4.3.3 which makes className a "core prop", which should make sure it's included by all renderers.

Do note that the code you have above will only address root-level components, but that might be OK depending on your use case?

For even more control, you can use custom renderers.
