### ISSUE TITLE
Syntax highlight

### ISSUE THREAD

**Issue by Yomguithereal** [rexxars/commonmark-react-renderer#5]
I remember reading somewhere that you were planning to do this @rexxars. What is your plan?

Would a code renderer option passed to the parser and taking a function returning raw HTML a solution?

**Comment by rexxars** [comment]
I'm planning to support custom elements for all types. With this in place, it's up to the user to select which highlighting solution they want to use, or what link handler they prefer, for instance.

**Comment by rexxars** [comment]
This should be possible now, with a custom renderer. It's basically just about creating a wrapper component for whatever highlighting library you want to use. I feel like I want to take a stab at an example sometime, but don't have time to do that tonight.
